name: Automated API tests using Postman CLI

on: push

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Install Newman and HTML Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make folder for results
        run: mkdir -p reports

      - name: Run API tests and generate reports
        run: |
          newman run "https://api.postman.com/collections/18644604-92e8c7d7-b11e-436d-9d92-9136b228cf17?access_key=${{ secrets.POSTMAN_API_KEY_NEWMAN }}" -r cli,htmlextra --reporter-htmlextra-export reports/report.html
      
      - name: Output the run details
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: reports
      
