name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Install Newman and HTML Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run API tests and generate reports
        run: |
          newman run "18644604-92e8c7d7-b11e-436d-9d92-9136b228cf17" -e "18644604-26f4a5e5-6767-416a-8d9e-b715015b6f7d" --reporters cli,htmlextra
